config/routes.rb
Rails.application.routes.draw do
  resources :forms do
    resources :versions, only: [:create, :destroy]
    resources :responses
  end

  resources :questions, only: [:update]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_response, :set_section
  helper_method :last_page?
  
  def new
    @response.answers.build(questions)
    @answers = @response.answers.filter { |a| a.question.parent == @section }
  end

  def edit
    @response.answers.build(questions)
    @answers = @response.answers.filter { |a| a.question.parent == @section }
  end

  def create
    if @response.update(response_parameters)
      go_to_next
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @response.update(response_parameters)
      go_to_next
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def go_to_next
    if last_page?
      redirect_to form_path(form)
    else
      redirect_to edit_form_response_path(form, @response, page: (params[:page] || 1) + 1)
    end
  end

  def questions
    @section.questions.map do |q| 
      next if @response.answers.find_by(question: q)
      if q.children.present?
        {question: q, children: q.children.map { |qq| Answer.find_or_initialize_by(question: qq, response: @response) }}
      else
        { question: q }
      end
    end.compact
  end

  def response_parameters
    params.require(:response).permit(answers_attributes: [:id, :question_id, :text])
  end

  def set_response
    @response ||= Response.find_by(id: params[:id]) || Response.new(version: form.latest)
  end

  def set_section
    @section ||= form.latest.sections.find_by(position: params[:page] || 1)
  end

  def last_page?
    @last = form.latest.sections.count == (params[:page].to_i || 1)
  end

  def form
    @_form ||= Form.find(params[:form_id])
  end
end

app/views/responses/_question.html.erb
<div class="w-full my-4">
  <h3 class="text-lg font-semibold mb-2"><%= "#{q.text}" %></h3>
  <%= f.hidden_field :id %>
  <%= f.hidden_field :question_id %>

  <%# This matches the Question model input type to a partial in display_form %>
  <%= render "display_form/#{q.input_type}", q:, children:, f: %>
</div>

app/views/responses/edit.html.erb
<div class="relative w-1/2 mx-auto border border-[#0003] rounded-lg p-4 mb-8">
  <div class="absolute -top-4 w-fit bg-white px-2 text-2xl font-bold"><%= @response.version.form.name %></div>
  <%= form_with(model: @response, url: form_response_path(@response.version.form, @response, page: params[:page])) do |f|  %>
    <%= f.fields_for :answers, @answers do |ff| %>
      <%= render "question", q: ff.object.question, children: ff.object.children, f: ff %>
    <% end %>
    <%= f.submit last_page? ? :Submit : :Next, class: "w-full cursor-pointer mt-6 rounded-lg bg-blue-600 hover:bg-blue-700 text-white py-2 px-4" %>
  <% end %>
</div>

app/views/responses/new.html.erb
<div class="relative w-1/2 mx-auto border border-[#0003] rounded-lg p-4 mb-8">
  <div class="absolute -top-4 w-fit bg-white px-2 text-2xl font-bold"><%= @response.version.form.name %></div>
  <%= form_with(model: @response, url: form_responses_path) do |f|  %>
    <%= f.fields_for :answers, @response.answers do |ff| %>
      <%= render "question", q: ff.object.question, children: ff.object.children, f: ff %>
    <% end %>
    <%= f.submit :Submit, class: "w-full cursor-pointer mt-6 rounded-lg bg-blue-600 hover:bg-blue-700 text-white py-2 px-4" %>
  <% end %>
</div>