config/routes.rb
Rails.application.routes.draw do
  resources :forms do
    resources :versions, only: [:create, :destroy]
    resources :responses
  end

  resources :questions, only: [:update]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, except: [:index]
  
  def index
  end

  def show
    @version = Version.find_by(id: params[:version]) || @form.latest
  end

  def new
  end

  def create
    @form = Form.create(form_parameters)
    if @form
      redirect_to form_path(@form)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @form.update(form_parameters)
      redirect_to form_path(@form)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_form
    @form ||= Form.find_by(id: params[:id]) || Form.new
  end 

  def form_parameters
    params.require(:form).permit(
                            :name, 
                            versions_attributes: [
                              :id,
                              :name,
                              :_destroy,
                              sections_attributes: [
                                :id,
                                :name,
                                questions_attributes: [
                                  *question_attributes,
                                  options: [],
                                  columns: [],
                                  children_attributes: [
                                    *question_attributes
                                  ]
                                ]
                              ]
                            ], 
                            
                          )
  end

  def question_attributes
    %i(id _destroy text input_type required)
  end
end

app/views/forms/_children.html.erb
<% form.fields_for :children do |ff| %>
  <%= ff.text_field :text, class: "mb-4" %>
<% end %>

<% form.fields_for :children, form.object.children.new do |ff| %>
  <template data-nested-form-target="template">
    <%= form.text_field :text, value: "", class: "mb-4" %>
  </template>
<% end %>

app/views/forms/_form.html.erb
<%= form.fields_for :versions, @form.latest || @form.versions.new  do |version_form| %>
  <div class="w-full flex gap-4 mb-4">
    <%= form.text_field :name, class: "grow disabled:cursor-not-allowed", disabled: @form.persisted?, placeholder: "Enter form name...", required: true %>
    <div class="relative max-w-[8rem]">
      <%= version_form.number_field :name, min: 1, class: "pl-8 w-full", placeholder: "1", required: true %>
      <div class="absolute top-1/2 transform -translate-y-1/2 left-4">v</div>
    </div>
    <%= version_form.hidden_field :id %>
  </div>

  <%= dynamic_fields_for version_form, :sections, "Add Section" do |section_form| %>
    <div class="border border-[#0004] rounded-lg p-4 my-4">
      <%= section_form.text_field :name, class: "mb-4", placeholder: "Section Title" %>
      <%= dynamic_fields_for section_form, :questions, "Add Questions" do |question_form| %>
        <%= render "field_creation", form: question_form %>
      <% end %>
    </div>
  <% end %>
<% end %>

<%= form.submit :Save, class: "cursor-pointer p-4 bg-blue-600 text-white hover:bg-blue-700 transition rounded-lg my-4 w-full" %>

app/views/forms/_grid.html.erb
<div class="grid grid-cols-2 w-full gap-4">
  <%= render "grid_rows", form:, q: %>
  <%= render "grid_columns", form:, q: %>
</div>

app/views/forms/_grid_columns.html.erb
<div data-controller="nested-form" data-nested-form-wrapper-selector-value=".nested-form-wrapper">
  <p class="text-lg font-semibold">Columns</p>
  <% q&.columns&.each do |column| %>
    <%= form.text_field :columns, value: column, multiple: true, class: "mb-4" %>
  <% end %>
  <div data-nested-form-target="target"></div>

  <template data-nested-form-target="template">
    <%= form.text_field :columns, value: "", multiple: true, class: "mb-4" %>
  </template>

  <button type="button" class="border border-[#0003] rounded-lg px-4 py-2" data-action="nested-form#add">Add Column</button>
</div>

app/views/forms/_grid_rows.html.erb
<div data-controller="nested-form" data-nested-form-wrapper-selector-value=".nested-form-wrapper">
  <p class="text-lg font-semibold">Rows</p>

  <%= form.fields_for :children, form.object.children do |ff| %>
    <%= ff.hidden_field :id %>
    <%= ff.hidden_field :input_type, value: :radio_buttons %>

    <%= ff.text_field :text, value: ff.object.text, class: "mb-4" %>
  <% end %>
  <%= form.fields_for :children, form.object.children.new do |ff| %>

    <div data-nested-form-target="target"></div>

    <template data-nested-form-target="template">
      <%= ff.hidden_field :input_type, value: :radio_buttons %>

      <%= ff.text_field :text, value: "", class: "mb-4" %>
    </template>

    <button type="button" class="border border-[#0003] rounded-lg px-4 py-2" data-action="nested-form#add">Add Row</button>
  <% end %>
</div>

app/views/forms/_optional_children.html.erb
<div class="hidden max-w-[600px]" data-controller="nested-form" data-nested-form-wrapper-selector-value=".nested-form-wrapper" data-dynamic-form-target="children">
  <%= render "children", form:, q: form.object %>
  <div data-nested-form-target="target"></div>

  <button type="button" class="border border-[#0003] rounded-lg px-4 py-2" data-action="nested-form#add">Add another sub question</button>
</div>

app/views/forms/_optional_grid.html.erb
<div class="hidden max-w-[600px]" data-dynamic-form-target="grid">
  <%= render "grid", form:, q: form.object %>
</div>

app/views/forms/_optional_options.html.erb
<div class="hidden max-w-[600px]" data-controller="nested-form" data-nested-form-wrapper-selector-value=".nested-form-wrapper" data-dynamic-form-target="options">
  <%= render "options", form:, q: form.object %>
  <div data-nested-form-target="target"></div>

  <button type="button" class="border border-[#0003] rounded-lg px-4 py-2" data-action="nested-form#add">Add option</button>
</div>

app/views/forms/_options.html.erb
<% q&.options&.each do |option| %>
  <%= form.text_field :options, value: option, multiple: true, class: "mb-4" %>
<% end %>

<template data-nested-form-target="template">
  <%= form.text_field :options, value: "", multiple: true, class: "mb-4" %>
</template>

app/views/forms/_question.html.erb
<div class="w-full my-4">
  <h3 class="text-lg font-semibold mb-2"><%= "#{idx + 1}. #{q.text}" %></h3>
  <% if q.input_type_radio_grid? %>
    <table class="w-full">
      <thead>
        <th></th>
        <% q.columns.each do |column| %>
          <th><%= column %></th>
        <% end %>
      </thead>
      <tbody>
        <%= f.fields_for :questions, q do |ff| %>
          <%= ff.fields_for :children, q.children do |fff| %>
            <tr>
              <td class="py-2 pl-2 w-2 whitespace-nowrap font-semibold"><%= fff.object.text %></td>
              <% q.columns.each do |column| %>
                <td class="text-center">
                  <%= fff.radio_button :text, column %>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <%= render "display_form/#{q.input_type}", q:, children: q.children, f: %>
  <% end %>
</div>

app/views/forms/edit.html.erb
<div class="flex flex-col gap-2 mx-auto pb-8">
  <%= form_with(model: @form, class: "mx-auto w-[700px]", url: form_path(@form)) do |form| %>
    <%= render "form", form: %>
  <% end %>
  <%= link_to "Cancel", form_version_path(@form), class: "text-center transition border border-red-500 hover:bg-red-500 text-red-500 hover:text-white rounded-lg p-4", data: { turbo_method: :delete, turbo_confirm: "Are you sure" } %>
</div>

app/views/forms/index.html.erb
<div class="w-3/4 mx-auto">
  <div class="flex w-full justify-between items-center mb-8">
    <h1 class="text-2xl font-bold">Forms</h1>
    <%= link_to "+", new_form_path, class: "h-10 w-10 flex justify-center items-center rounded-full bg-blue-600 hover:bg-blue-700 font-bold text-white" %>
  </div>
  <% Form.all.each do |form| %>
    <div class="flex flex-col gap-4 my-4 pb-2 border-b-2 last:border-b-0 border-[#0003]">
      <%= link_to form_path(form), class: "w-full h-full" do %>
        <h3 class="text-lg font-semibold">
          <%= form.name %>
        </h3>
        <p class="text-base font-thin"><%= form.latest.name %></p>
      <% end %>
      <%= link_to "Start FQ", new_form_response_path(form), class: "w-fit py-2 px-4 rounded-lg transition border border-blue-600 hover:bg-blue-700 text-blue-700 hover:text-white transition" %>
    </div>
  <% end %>
</div>

app/views/forms/new.html.erb
<%= form_with(model: @form, class: "mx-auto w-[700px]", url: forms_path) do |form| %>
  <%= render "form", form: %>
<% end %>

app/views/forms/show.html.erb
<div class="flex flex-col gap-6 w-full sm:w-1/2 mx-auto">
  <%= link_to "< Back", forms_path, class: "w-fit font-semibold text-sm" %>
  <div class="flex w-full justify-between items-center">
    <h1 class="text-2xl font-bold"><%= @form.name%></h1>
    <div class="flex gap-6">
      <%= form_with(model: Version.new, url: form_versions_path(@form)) do |f| %>
        <%= f.hidden_field :name, value: "v 0.0.3" %>
        <%= f.submit "+ New Version", class: "py-2 px-4 bg-blue-600 rounded-lg hover:bg-blue-700 cursor-pointer text-white" %>
      <% end %>
      <div data-controller="dropdown" class="relative z-10 bg-white">
        <div class="absolute top-1/2 transform -translate-y-1/2 left-4">v</div>
        <button type="button" class="w-[7rem] flex rounded-lg border border-b-gray-300 py-2 pl-8" data-action="dropdown#toggle click@window->dropdown#hide">
          <%= @version.name %>
        </button>
        <div
        data-dropdown-target="menu"
        class="w-full bg-white hidden transition transform origin-top-right absolute right-0 pt-2 border-x border-b border-gray-300 rounded-b-lg"
        data-transition-enter-from="opacity-0 scale-95"
        data-transition-enter-to="opacity-100 scale-100"
        data-transition-leave-from="opacity-100 scale-100"
        data-transition-leave-to="opacity-0 scale-95"
      >
          <% @form.versions.each do |version| %>
            <%= link_to "v #{version.name}", 
                      form_path(@form, version: version.id), 
                      class: "w-full inline-block py-2 px-4 hover:bg-gray-200 transition w-full h-full rounded-lg", 
                      data: { action: "dropdown#toggle" } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <%= form_with(model: @form) do |f|  %>
    <% @version.sections.each do |section| %>
      <div class="relative rounded-lg p-4 border border-gray-300 pt-8 mb-8">
        <div class="absolute -top-4 w-fit px-2 bg-white text-lg font-bold">
          <%= section.name %>
        </div>
        <% section.questions.each_with_index do |question, idx| %>
          <%= render "question", q: question, idx:, f: %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>